[project]
name = "IBKR_StockAPI_Wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "akshare>=1.17.26",
    "ib-async>=2.0.1",
    "ibapi>=9.81.1.post1",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
]
